project_name: eddwise
builds:
  - goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    id: "eddwise"
    binary: edd
    dir: .
    main: ./cmd/edd
