$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://github.com/exelr/eddwise/schema.yml"
.enum: &typeEnum
  - int
  - int8
  - int16
  - int32
  - int64
  - uint
  - uint8
  - uint16
  - uint32
  - uint64
  - string
  - "[]byte"
type: object
required:
  - namespace
properties:
  namespace:
    type: string
  structs:
    type: object
    patternProperties:
      ".*":
        type: object
        additionalProperties: false
        properties:
          alias:
            type: string
          fields:
            type: object
            patternProperties:
              ".*":
                anyOf:
                  - enum: *typeEnum
#                  - type: &typeStr
#                    enum:
#                      $data: "/structs#"
                  - type: object
                    additionalProperties: false
                    properties:
                      alias:
                        type: string
                      type:
                        anyOf: *typeEnum



  channels:
    type: object
    patternProperties:
      ".*":
        type: object
        additionalProperties: false
        required:
          - enable
        properties:
          alias:
            type: string
          enable:
            type: array
            items:
              type: string
              enum:
                $data: "/structs#"
